### ISSUE TITLE
adding admins section in readme 

### ISSUE THREAD

**Issue by Ayan-thecodeking** [Feminine-Divine/Woodog#38] opened 2021-06-14 15:09 UTC

**Comment by hariramjp777** [comment] 2021-06-14 15:10
Can you please briefly explain what the issue is?

**Comment by Ayan-thecodeking** [comment] 2021-06-14 15:11
hey @hariramjp777 please assign me this 
just want to add admins sections ....i mean maintainers section
i'll fix it for sure :)

**Comment by Sejal2801** [comment] 2021-06-14 17:18
Please assign it to me

**Comment by Sejal2801** [comment] 2021-06-14 17:21
Assign it to me plz

**Comment by Ayan-thecodeking** [comment] 2021-06-14 18:36
> Hi @Ayan-thecodeking, Can you please briefly explain what the issue is?

hey @Sejal2801  i have already asked please look for another issue :)

**Comment by Ayan-thecodeking** [comment] 2021-06-14 18:37
> Assign it to me plz

hey  @Sejal2801  i have already asked please look for another issues :)

**Closed** 2021-06-15 21:25 UTC
Labels: LGMSOC21, documentation, 🟨 Level2
